# Generated by Django 5.1.6 on 2025-03-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_company_owned',
            field=models.BooleanField(default=False),
        ),
    ]
