# Generated by Django 5.1.6 on 2025-04-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('2 Ton Truck', '2 Ton Truck'), ('4 Ton Truck', '4 Ton Truck'), ('6 Ton Truck', '6 Ton Truck')], max_length=50),
        ),
    ]
