# Generated by Django 5.1.6 on 2025-04-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salary'),
        ),
        migrations.AlterField(
            model_name='salaryconfiguration',
            name='label',
            field=models.CharField(blank=True, help_text="Optional label like 'Jan 2025 Config' or 'Updated Rates'", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='SalaryReport',
        ),
    ]
