# Generated by Django 5.1.6 on 2025-03-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary_configuration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='assignment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reassigned', 'Reassigned')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default='Philippines', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.employee'),
        ),
        migrations.AddField(
            model_name='trip',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_trips', to='api.employee'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='region',
            field=models.CharField(blank=True, choices=[('Region I', 'Region I – Ilocos Region'), ('Region II', 'Region II – Cagayan Valley'), ('Region III', 'Region III – Central Luzon'), ('Region IV‑A', 'Region IV‑A – CALABARZON'), ('MIMAROPA', 'MIMAROPA Region'), ('Region V', 'Region V – Bicol Region'), ('Region VI', 'Region VI – Western Visayas'), ('Region VII', 'Region VII – Central Visayas'), ('Region VIII', 'Region VIII – Eastern Visayas'), ('Region IX', 'Region IX – Zamboanga Peninsula'), ('Region X', 'Region X – Northern Mindanao'), ('Region XI', 'Region XI – Davao Region'), ('Region XII', 'Region XII – SOCCSKSARGEN'), ('Region XIII', 'Region XIII – Caraga'), ('NCR', 'NCR – National Capital Region'), ('CAR', 'CAR – Cordillera Administrative Region'), ('BARMM', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao'), ('NIR', 'NIR – Negros Island Region')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='street_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Driver', 'Driver'), ('Helper', 'Helper'), ('Staff', 'Staff'), ('Not Applicable', 'Not Applicable')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_company_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='client_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='curr_drops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance_traveled',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='num_of_drops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=15, null=True),
        ),
    ]
