# Generated by Django 5.1.6 on 2025-04-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryconfiguration',
            name='label',
        ),
    ]
