# Generated by Django 5.1.6 on 2025-04-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='subcon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
