# Generated by Django 5.1.6 on 2025-03-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicle_is_company_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.employee'),
        ),
    ]
