# Generated by Django 5.1.6 on 2025-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_employee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='multipliers',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='overtime',
        ),
        migrations.AlterField(
            model_name='salary',
            name='additionals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
