# Generated by Django 5.1.6 on 2025-04-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_salaryconfiguration_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salary'),
        ),
    ]
