# Generated by Django 5.1.6 on 2025-04-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_total_salary_alter_salaryconfiguration_label_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeLocation',
        ),
    ]
