# Generated by Django 5.1.6 on 2025-04-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_salaryconfiguration_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfiguration',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trip'),
        ),
    ]
