# Generated by Django 5.1.6 on 2025-04-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_total_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryReport',
        ),
    ]
