# Generated by Django 5.1.6 on 2025-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehicle_subcon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
