# Generated by Django 5.1.6 on 2025-03-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_salary_deductions_remove_salary_multipliers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='salary_report',
        ),
    ]
