# Generated by Django 5.1.6 on 2025-03-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_employee_trip_trip_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_trips', to='api.employee'),
        ),
    ]
