# Generated by Django 5.1.6 on 2025-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_salaryconfiguration_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
