# Generated by Django 5.1.6 on 2025-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_total_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='helper_base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
