# Generated by Django 5.1.6 on 2025-03-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trip_helper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default='Philippines', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='street_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
