# Generated by Django 5.1.6 on 2025-03-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_administrator_salary_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='assignment_status',
        ),
    ]
