# Generated by Django 5.1.6 on 2025-03-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_trip_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='helper2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper2_trips', to='api.employee'),
        ),
    ]
