# Generated by Django 5.1.6 on 2025-03-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_trip_destination_trip_barangay_trip_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
