# Generated by Django 5.1.6 on 2025-04-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_totals_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
