# Generated by Django 5.1.6 on 2025-02-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_employee_type_alter_employee_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='salary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salaryreport'),
        ),
        migrations.AlterField(
            model_name='salaryreport',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='salaryreport',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salary'),
        ),
    ]
