# Generated by Django 5.1.6 on 2025-04-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trip_date_created_trip_helper_base_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_description',
            field=models.CharField(choices=[('Frozen', 'Frozen'), ('Chilled', 'Chilled'), ('Dry', 'Dry'), ('Skin', 'Skin')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[('Foul', 'Foul'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
