# Generated by Django 5.1.6 on 2025-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trip_trip_description_trip_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='others_description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
