# Generated by Django 5.1.6 on 2025-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trip_helper2'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='addresses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
