# Generated by Django 5.1.6 on 2025-04-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_salary_others_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='bonuses',
        ),
    ]
