# Generated by Django 5.1.6 on 2025-03-24 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_trip_client_info_alter_trip_curr_drops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Area code must contain only digits.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='region',
            field=models.CharField(blank=True, choices=[('Select a Region', ''), ('Region I', 'Region I – Ilocos Region'), ('Region II', 'Region II – Cagayan Valley'), ('Region III', 'Region III – Central Luzon'), ('Region IV‑A', 'Region IV‑A – CALABARZON'), ('MIMAROPA', 'MIMAROPA Region'), ('Region V', 'Region V – Bicol Region'), ('Region VI', 'Region VI – Western Visayas'), ('Region VII', 'Region VII – Central Visayas'), ('Region VIII', 'Region VIII – Eastern Visayas'), ('Region IX', 'Region IX – Zamboanga Peninsula'), ('Region X', 'Region X – Northern Mindanao'), ('Region XI', 'Region XI – Davao Region'), ('Region XII', 'Region XII – SOCCSKSARGEN'), ('Region XIII', 'Region XIII – Caraga'), ('NCR', 'NCR – National Capital Region'), ('CAR', 'CAR – Cordillera Administrative Region'), ('BARMM', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao'), ('NIR', 'NIR – Negros Island Region')], default='Select a Region', max_length=50, null=True),
        ),
    ]
