# Generated by Django 5.1.6 on 2025-03-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trip_clients_trip_completed_trip_dest_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='client_info',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='curr_drops',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_latitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_longitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='distance_traveled',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='province',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='region',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user_latitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user_longitude',
        ),
        migrations.AddField(
            model_name='trip',
            name='distances',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
