# Generated by Django 5.1.6 on 2025-04-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_salary_bonuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='base_salary',
            new_name='driver_base_salary',
        ),
    ]
