# Generated by Django 5.1.6 on 2025-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_trip_barangay_remove_trip_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='additionals',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='base_salary',
        ),
        migrations.AddField(
            model_name='trip',
            name='additionals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
