# Generated by Django 5.1.6 on 2025-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_trip_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='assignment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reassigned', 'Reassigned')], default='pending', max_length=20),
        ),
    ]
