# Generated by Django 5.1.6 on 2025-04-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_base_salary_trip_driver_base_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
