# Generated by Django 5.1.7 on 2025-03-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_trip_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
