# Generated by Django 5.1.6 on 2025-04-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_trip_trip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[('Foul', 'Foul'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Ongoing', 'Ongoing')], max_length=50, null=True),
        ),
    ]
