# Generated by Django 5.1.6 on 2025-04-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_trip_is_in_progress_alter_trip_additionals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
