# Generated by Django 5.1.6 on 2025-04-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_trip_trip_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[('Foul', 'Foul'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Ongoing', 'Ongoing'), ('Pending', 'Pending')], max_length=50, null=True),
        ),
    ]
