# Generated by Django 5.1.6 on 2025-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_trip_user_lat_alter_trip_user_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='vale',
            new_name='bale',
        ),
        migrations.AddField(
            model_name='salary',
            name='pagibig_contribution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='philhealth_contribution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='sss_contribution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
