# Generated by Django 5.1.6 on 2025-03-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_trip_is_completed_trip_status'),
        ('api', '0012_remove_employee_salary_configuration'),
    ]

    operations = [
    ]
