# Generated by Django 5.1.6 on 2025-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20250328_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
        migrations.AddField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
