# Generated by Django 5.1.6 on 2025-04-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_vale_salary_bale_salary_pagibig_contribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='pagibig_contribution',
        ),
        migrations.AddField(
            model_name='salaryconfiguration',
            name='pagibig_contribution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
