# Generated by Django 5.1.6 on 2025-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_trip_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelocation',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
