# Generated by Django 5.1.6 on 2025-03-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_trip_status_trip_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Driver', 'Driver'), ('Helper', 'Helper'), ('Staff', 'Staff')], max_length=50, null=True),
        ),
    ]
