# Generated by Django 5.1.6 on 2025-04-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_salary_pagibig_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Driver', 'Driver'), ('Helper', 'Helper'), ('Staff', 'Staff')], max_length=50, null=True),
        ),
    ]
