# Generated by Django 5.1.6 on 2025-04-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='completed_trip_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
