# Generated by Django 5.1.6 on 2025-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_employee_employee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Driver', 'Driver'), ('Helper', 'Helper'), ('Staff', 'Staff')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=15, null=True),
        ),
    ]
