# Generated by Django 5.1.6 on 2025-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_trip_trip_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryconfiguration',
            old_name='pagibig_percentage',
            new_name='pagibig_loan',
        ),
        migrations.RenameField(
            model_name='salaryconfiguration',
            old_name='philhealth_percentage',
            new_name='philhealth_contribution',
        ),
        migrations.RenameField(
            model_name='salaryconfiguration',
            old_name='sss_percentage',
            new_name='sss_contribution',
        ),
        migrations.AddField(
            model_name='salaryconfiguration',
            name='sss_loan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
