# Generated by Django 5.1.6 on 2025-04-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_pagibig_percentage_salaryconfiguration_pagibig_loan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='total_bonuses',
        ),
    ]
