# Generated by Django 5.1.6 on 2025-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_employee_employee_type_user_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Driver', 'Driver'), ('Helper', 'Helper'), ('Staff', 'Staff'), ('Not Applicable', 'Not Applicable')], max_length=50, null=True),
        ),
    ]
