# Generated by Django 5.1.6 on 2025-03-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Helper', 'Helper'), ('Staff', 'Staff'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50, null=True),
        ),
    ]
